[variables]
PYTHON_VERSION = "3.10"

[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = ["python -m venv /app/.venv", ". /app/.venv/bin/activate && pip install --upgrade pip setuptools wheel", ". /app/.venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". /app/.venv/bin/activate && gunicorn Mushroom_Edibility.wsgi:application"
